#!/bin/bash
clear
echo "NutChain Linaro 7.2 R11/17 SN"
echo "Setting up toolchain for use"
rm -rf .git
cd libexec/gcc/x86_64-linux-gnu/7.2.1
echo "******[You must have tar & cat installed to make this TC useable]******"
echo "Rebuilding tarfile"
cat execlib* > execlib.tar.xz
echo "Untaring Files"
tar -axvf execlib.tar.xz
echo "Removing Temp files"
rm -f execlib*
echo "All done"
echo " "
echo " "
echo "Use these export commands now"
echo " "
echo "export ARCH=x86_64"
echo "export CROSS_COMPILE=x86_64-linux-"
echo "export CCOMPILE=$CROSS_COMPILE"
echo " "
echo " "
echo "Happy compiling :) "
echo "Script by nutcasev1.5"
